### PR TITLE
fixed infinite loop in CGI files and added test scripts

### LINKED ISSUE #54: CGI scripts get stuck if they have an infinite loop
Need to fix the infinite loop

### PR DESCRIPTION
**Pull request by Bravnar**
Added time() around waitpid and set "alarm" for 5 seconds, the scripts will timeout after 5 seconds if infinite loop is detected, if there is an error in the script, 500 is thrown.

fixes #54

### CODE REVIEW

File: src/classes/CgiHandler.cpp [hunk 1]
```diff
@@ -197,10 +219,35 @@ void	CgiHandler::_execPost( const std::string &scriptPath ) {
 		char		buffer[1024] ;
```
Comment (RPDJF) [inline src/classes/CgiHandler.cpp:219]: i never mentioned it, but in your next pr, can you include DF_MAX_BUFFER instead of hardcoding 1024 ?
DF_MAX_BUFFER is by default set to 8192 -> after some research, it seems to be the best value since it fits the majority of cpu primary cache

File: src/classes/CgiHandler.cpp [hunk 2]
```diff
@@ -141,22 +145,38 @@ void	CgiHandler::_execGet( const std::string &scriptPath ) {
...
 		while ((bytesRead = read( pipefd[0], buffer, sizeof(buffer) - 1)) > 0) output.append(buffer, bytesRead) ; 
 
 		close( pipefd[0] ) ;
-			waitpid( pid, NULL, WNOHANG ) ;
-		// TODO: handle infinite loop in the script
+
+		int status ;
+		time_t	startTime = time(NULL) ;
+		while (waitpid( pid, &status, WNOHANG ) == 0 ) {
+			if (time(NULL) - startTime > 5 ) {
```
Comment (RPDJF) [inline src/classes/CgiHandler.cpp:169]: maybe 1 second or even less ?
it will block the other clients during this period

File: src/classes/CgiHandler.cpp [hunk 3]
```diff
@@ -141,22 +145,38 @@ void	CgiHandler::_execGet( const std::string &scriptPath ) {
...
+				Logger::error("CGI Execution timed out!\n") ;
```
Comment (RPDJF) [inline src/classes/CgiHandler.cpp:170]: this error comes even when it has nothing to do with timeout reaching
exemple where i just removed a ;
```
[2025-02-28 21:28:31.9926] [INFO] Runtime: default: Request GET /cgi-php/ client 127.0.0.1
PHP Parse error:  syntax error, unexpected variable "$content", expecting "," or ";" in /home/ruipa/42_webserv/www/cgi-php/index.php on line 12
[2025-02-28 21:28:32.32] [ERROR] CGI Error: Infinite loop in script.

[2025-02-28 21:28:32.34] [FATAL] Runtime: default: Response 500 Internal Server Error for GET /cgi-php/ client 127.0.0.1
[2025-02-28 21:28:32.776] [INFO] Runtime: default: Request GET /favicon.ico client 127.0.0.1
[2025-02-28 21:28:32.779] [INFO] Runtime: default: Response 200 OK for GET /favicon.ico client 127.0.0.1
```

**Review by RPDJF — CHANGES_REQUESTED** [review]
i commented some parts

File: src/classes/CgiHandler.cpp (hunk 1 above)
Comment (Bravnar) [reply src/classes/CgiHandler.cpp:219]: Done

File: src/classes/CgiHandler.cpp (hunk 2 above)
Comment (Bravnar) [reply src/classes/CgiHandler.cpp:169]: brought it down to 1

File: src/classes/CgiHandler.cpp (hunk 3 above)
Comment (Bravnar) [reply src/classes/CgiHandler.cpp:170]: The errors messages were messed up. I fixed it to be clearer
